### ISSUE TITLE
Forge 1621: Logging into a non-byte dimension

### ISSUE THREAD

**Issue by keybounce** [MinecraftForkage/MinecraftForge#1]
Forge currently does not support a player logging into a dimension outside of the byte range (-128 to +127). The issue is a vanilla protocol issue in the login dimension. It is duplicated with the packet for maps (maps only work in -128 to +127).

However, moving a player supports the full integer range of dimensions.

The simple fix would be to just say that MinecraftForkage can change the protocol used; a vanilla client cannot connect to a forkage server.

More complicated solutions (logging on into a temporary dimension, and then moving you to the target dimension) were discussed on the forge issue; Lex has said that vanilla client compatibility is a "must" for 1.8.

Forge issue link: https://github.com/MinecraftForge/MinecraftForge/issues/1621

**Comment by immibis** [comment]
What's a simple way to reproduce the issue? Install Mystcraft and create 128-ish descriptive books, then go to the last one, log out and back in?

**Comment by keybounce** [comment]
Yep.

I ran into this in a testing world for the current mystcraft dev release. I was on dimension 129 when this happened to me.

**Comment by immibis** [comment]
Heh, apparently Github recognizes "Fixed &lt;URL of issue&gt;" in commit messages

**Comment by keybounce** [comment]
Grr ... where's the release with this?
Or do I have to download the source tree and compile it myself?

**Comment by immibis** [comment]
There isn't a build server (right now) so http://puu.sh/fVmC5.jar

**Comment by immibis** [comment]
Note that CodeChicken Core doesn't like Minecraft Forkage.

**Comment by keybounce** [comment]
On 2015-02-14, at 2:49 PM, immibis notifications@github.com wrote:

> Note that CodeChicken Core doesn't like Minecraft Forkage.

OUCH, that means NEI and Waila ...

...
Meanwhile, thank you for the build ... 

Do you know what CCC dislikes / any idea if it's likely to be easy to fix or not?

---

Entertaining minecraft videos
http://YouTube.com/keybounce
